Started logging messages at Fri Oct 26 23:49:55 2018
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 348 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 59
Info:            Created 
Info:        Working on 79
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 77
Info:            Created 
Info:        Working on 105
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 102
Info:            Created 
Info:        Working on 139
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 138
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 29
Info:            Created 
Info:        Working on 189
Info:            Created 
Info:        Working on 268
Info:            Created 
Info:        Working on 43
Info:            Created 
Info:        Working on 267
Info:            Created 
Info:        Working on 404
Info:            Created 
Info:        Working on 63
Info:            Created 
Info:        Working on 403
Info:            Created 
Info:        Working on 613
Info:            Created 
Info:        Working on 88
Info:            Created 
Info:        Working on 612
Info:            Created 
Info:        Working on 908
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 907
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 958
Info:            Created 
Info:        Working on 252
Info:            Created 
Info:        Working on 1322
Info:            Created 
Info:        Working on 388
Info:            Created 
Info:        Working on 1733
Info:            Created 
Info:        Working on 603
Info:            Created 
Info:        Working on 2534
Info:            Created 
Info:        Working on 2983
Info:            Created 
Info:        Working on 905
Info:            Created 
Info:        Working on 2982
Info:            Created 
Info:        Working on 2811
Info:            Created 
Info:        Working on 1275
Info:            Created 
Info:        Working on 3455
Info:            Created 
Info:        Working on 2393
Info:            Created 
Info:        Working on 1697
Info:            Created 
Info:        Working on 3546
Info:            Created 
Info:        Working on 1972
Info:            Created 
Info:        Working on 2118
Info:            Created 
Info:        Working on 1541
Info:            Created 
Info:        Working on 1962
Info:            Created 
Info:        Working on 531
Info:            Created 
Info:        Working on 799
Info:            Created 
Info:        Working on 796
Info:            Created 
Info:        Working on 1137
Info:            Created 
Info:        Working on 1134
Info:            Created 
Info:        Working on 1545
Info:            Created 
Info:        Working on 3323
Info:            Created 
Info:        Working on 3709
Info:            Created 
Info:        Working on 3941
Info:            Created 
Info:        Working on 4148
Info:            Created 
Info:        Working on 1968
Info:            Created 
Info:        Working on 4146
Info:            Created 
Info:        Working on 4258
Info:            Created 
Info:        Working on 2391
Info:            Created 
Info:        Working on 3947
Info:            Created 
Info:        Working on 4898
Info:            Created 
Info:        Working on 2815
Info:            Created 
Info:        Working on 4897
Info:            Created 
Info:        Working on 5154
Info:            Created 
Info:        Working on 3254
Info:            Created 
Info:        Working on 5153
Info:            Created 
Info:        Working on 5376
Info:            Created 
Info:        Working on 3698
Info:            Created 
Info:        Working on 5375
Info:            Created 
Info:        Working on 5602
Info:            Created 
Info:        Working on 4139
Info:            Created 
Info:        Working on 5601
Info:            Created 
Info:        Working on 5803
Info:            Created 
Info:        Working on 4539
Info:            Created 
Info:        Working on 5802
Info:            Created 
Info:        Working on 5973
Info:            Created 
Info:        Working on 4884
Info:            Created 
Info:        Working on 5094
Info:            Created 
Info:        Working on 4654
Info:            Created 
Info:        Working on 4974
Info:            Created 
Info:        Working on 5822
Info:            Created 
Info:        Working on 6168
Info:            Created 
Info:        Working on 5208
Info:            Created 
Info:        Working on 6167
Info:            Created 
Info:        Working on 6324
Info:            Created 
Info:        Working on 5426
Info:            Created 
Info:        Working on 6000
Info:            Created 
Info:        Working on 6002
Info:            Created 
Info:        Working on 5630
Info:            Created 
Info:        Working on 4058
Info:            Created 
Info:        Working on 3821
Info:            Created 
Info:        Working on 4260
Info:            Created 
Info:        Working on 416
Info:            Created 
Info:        Working on 706
Info:            Created 
Info:        Working on 627
Info:            Created 
Info:        Working on 766
Info:            Created 
Info:        Working on 342
Info:            Created 
Info:        Working on 534
Info:            Created 
Info:        Working on 1096
Info:            Created 
Info:        Working on 2764
Info:            Created 
Info:        Working on 802
Info:            Created 
Info:        Working on 1910
Info:            Created 
Info:        Working on 3267
Info:            Created 
Info:        Working on 1143
Info:            Created 
Info:        Working on 2340
Info:            Created 
Info:        Working on 3710
Info:            Created 
Info:        Working on 1553
Info:            Created 
Info:        Working on 1494
Info:            Created 
Info:        Working on 3206
Info:            Created 
Info:        Working on 1913
Info:            Created 
Info:        Working on 2126
Info:            Created 
Info:        Working on 1025
Info:            Created 
Info:        Working on 1410
Info:            Created 
Info:        Working on 1705
Info:            Created 
Info:        Working on 1817
Info:            Created 
Info:        Working on 1819
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Working on 2231
Info:            Created 
Info:        Working on 1707
Info:            Created 
Info:        Working on 919
Info:            Created 
Info:        Working on 1406
Info:            Created 
Info:        Working on 1288
Info:            Created 
Info:        Working on 954
Info:            Created 
Info:        Working on 1301
Info:            Created 
Info:        Working on 1633
Info:            Created 
Info:        Working on 1308
Info:            Created 
Info:        Working on 1709
Info:            Created 
Info:        Working on 570
Info:            Created 
Info:        Working on 1211
Info:            Created 
Info:        Working on 569
Info:            Created 
Info:        Working on 858
Info:            Created 
Info:        Working on 1622
Info:            Created 
Info:        Working on 1623
Info:            Created 
Info:        Working on 845
Info:            Created 
Info:        Working on 1201
Info:            Created 
Info:        Working on 667
Info:            Created 
Info:        Working on 668
Info:            Created 
Info:        Working on 965
Info:            Created 
Info:        Working on 1333
Info:            Created 
Info:        Working on 1741
Info:            Created 
Info:        Working on 2151
Info:            Created 
Info:        Working on 2163
Info:            Created 
Info:        Working on 1754
Info:            Created 
Info:        Working on 1343
Info:            Created 
Info:        Working on 976
Info:            Created 
Info:        Working on 144
Info:            Created 
Info:        Working on 953
Info:            Created 
Info:        Working on 1725
Info:            Created 
Info:        Working on 2141
Info:            Created 
Info:        Working on 2542
Info:            Created 
Info:        Working on 2554
Info:            Created 
Info:        Working on 2144
Info:            Created 
Info:        Working on 1731
Info:            Created 
Info:        Working on 1314
Info:            Created 
Info:        Working on 196
Info:            Created 
Info:        Working on 852
Info:            Created 
Info:        Working on 279
Info:            Created 
Info:        Working on 482
Info:            Created 
Info:        Working on 481
Info:            Created 
Info:        Working on 419
Info:            Created 
Info:        Working on 1579
Info:            Created 
Info:        Working on 2128
Info:            Created 
Info:        Working on 1608
Info:            Created 
Info:        Working on 833
Info:            Created 
Info:        Working on 631
Info:            Created 
Info:        Working on 2433
Info:            Created 
Info:        Working on 2021
Info:            Created 
Info:        Working on 2860
Info:            Created 
Info:        Working on 2419
Info:            Created 
Info:        Working on 930
Info:            Created 
Info:        Working on 889
Info:            Created 
Info:        Working on 1677
Info:            Created 
Info:        Working on 1249
Info:            Created 
Info:        Working on 2089
Info:            Created 
Info:        Working on 2489
Info:            Created 
Info:        Working on 2928
Info:            Created 
Info:        Working on 3378
Info:            Created 
Info:        Working on 3482
Info:            Created 
Info:        Working on 3010
Info:            Created 
Info:        Working on 2491
Info:            Created 
Info:        Working on 1296
Info:            Created 
Info:        Working on 1656
Info:            Created 
Info:        Working on 870
Info:            Created 
Info:        Working on 1762
Info:            Created 
Info:        Working on 2175
Info:            Created 
Info:        Working on 2577
Info:            Created 
Info:        Working on 2826
Info:            Created 
Info:        Working on 2403
Info:            Created 
Info:        Working on 2402
Info:            Created 
Info:        Working on 2066
Info:            Created 
Info:        Working on 1224
Info:            Created 
Info:        Working on 1652
Info:            Created 
Info:        Working on 1264
Info:            Created 
Info:        Working on 2159
Info:            Created 
Info:        Working on 3486
Info:            Created 
Info:        Working on 4269
Info:            Created 
Info:        Working on 4324
Info:            Created 
Info:        Working on 4704
Info:            Created 
Info:        Working on 5009
Info:            Created 
Info:        Working on 5228
Info:            Created 
Info:        Working on 5040
Info:            Created 
Info:        Working on 4751
Info:            Created 
Info:        Working on 3028
Info:            Created 
Info:        Working on 2185
Info:            Created 
Info:        Working on 1359
Info:            Created 
Info:        Working on 1238
Info:            Created 
Info:        Working on 2475
Info:            Created 
Info:        Working on 3364
Info:            Created 
Info:        Working on 3813
Info:            Created 
Info:        Working on 4252
Info:            Created 
Info:        Working on 4650
Info:            Created 
Info:        Working on 4969
Info:            Created 
Info:        Working on 4987
Info:            Created 
Info:        Working on 4668
Info:            Created 
Info:        Working on 4274
Info:            Created 
Info:        Working on 3837
Info:            Created 
Info:        Working on 3389
Info:            Created 
Info:        Working on 2511
Info:            Created 
Info:        Working on 5036
Info:            Created 
Info:        Working on 4741
Info:            Created 
Info:        Working on 5218
Info:            Created 
Info:        Working on 5217
Info:            Created 
Info:        Working on 5034
Info:            Created 
Info:        Working on 4744
Info:            Created 
Info:        Working on 5038
Info:            Created 
Info:        Working on 5037
Info:            Created 
Info:        Working on 2068
Info:            Created 
Info:        Working on 2662
Info:            Created 
Info:        Working on 1842
Info:            Created 
Info:        Working on 2261
Info:            Created 
Info:        Working on 1436
Info:            Created 
Info:        Working on 2256
Info:            Created 
Info:        Working on 3089
Info:            Created 
Info:        Working on 3537
Info:            Created 
Info:        Working on 4426
Info:            Created 
Info:        Working on 3557
Info:            Created 
Info:        Working on 2656
Info:            Created 
Info:        Working on 3098
Info:            Created 
Info:        Working on 4000
Info:            Created 
Info:        Working on 3827
Info:            Created 
Info:        Working on 3208
Info:            Created 
Info:        Working on 2769
Info:            Created 
Info:        Working on 2665
Info:            Created 
Info:        Working on 4810
Info:            Created 
Info:        Working on 3998
Info:            Created 
Info:        Working on 4430
Info:            Created 
Info:        Working on 3109
Info:            Created 
Info:        Working on 2223
Info:            Created 
Info:        Working on 1396
Info:            Created 
Info:        Working on 698
Info:            Created 
Info:        Working on 1007
Info:            Created 
Info:        Working on 1385
Info:            Created 
Info:        Working on 1803
Info:            Created 
Info:        Working on 2627
Info:            Created 
Info:        Working on 3070
Info:            Created 
Info:        Working on 3520
Info:            Created 
Info:        Working on 3965
Info:            Created 
Info:        Working on 4396
Info:            Created 
Info:        Working on 4770
Info:            Created 
Info:        Working on 5059
Info:            Created 
Info:        Working on 5099
Info:            Created 
Info:        Working on 4829
Info:            Created 
Info:        Working on 4473
Info:            Created 
Info:        Working on 4080
Info:            Created 
Info:        Working on 3645
Info:            Created 
Info:        Working on 3198
Info:            Created 
Info:        Working on 2751
Info:            Created 
Info:        Working on 1896
Info:            Created 
Info:        Working on 1474
Info:            Created 
Info:        Working on 1082
Info:            Created 
Info:        Working on 757
Info:            Created 
Info:        Working on 1487
Info:            Created 
Info:        Working on 1988
Info:            Created 
Info:        Working on 1989
Info:            Created 
Info:        Working on 2400
Info:            Created 
Info:        Working on 1391
Info:            Created 
Info:        Working on 716
Info:            Created 
Info:        Working on 1036
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 1823
Info:            Created 
Info:        Working on 1809
Info:            Created 
Info:        Working on 2572
Info:            Created 
Info:        Working on 3018
Info:            Created 
Info:        Working on 2249
Info:            Created 
Info:        Working on 1049
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 109
Info:            Created 
Info:        Working on 697
Info:            Created 
Info:        Working on 148
Info:            Created 
Info:        Working on 1004
Info:            Created 
Info:        Working on 1005
Info:            Created 
Info:        Working on 1378
Info:            Created 
Info:        Working on 1792
Info:            Created 
Info:        Working on 2205
Info:            Created 
Info:        Working on 2609
Info:            Created 
Info:        Working on 3051
Info:            Created 
Info:        Working on 3502
Info:            Created 
Info:        Working on 3456
Info:            Created 
Info:        Working on 3054
Info:            Created 
Info:        Working on 2613
Info:            Created 
Info:        Working on 2215
Info:            Created 
Info:        Working on 202
Info:            Created 
Info:        Working on 1372
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Working on 2195
Info:            Created 
Info:        Working on 2196
Info:            Created 
Info:        Working on 672
Info:            Created 
Info:        Working on 2198
Info:            Created 
Info:        Working on 3034
Info:            Created 
Info:        Working on 987
Info:            Created 
Info:        Working on 3042
Info:            Created 
Info:        Working on 1363
Info:            Created 
Info:        Working on 3499
Info:            Created 
Info:        Working on 3500
Info:            Created 
Info:        Working on 1774
Info:            Created 
Info:        Working on 521
Info:            Created 
Info:        Working on 522
Info:            Created 
Info:        Working on 777
Info:            Created 
Info:        Working on 1108
Info:            Created 
Info:        Working on 1509
Info:            Created 
Info:        Working on 1926
Info:            Created 
Info:        Working on 2352
Info:            Created 
Info:        Working on 2479
Info:            Created 
Info:        Working on 2465
Info:            Created 
Info:        Working on 1907
Info:            Created 
Info:        Working on 1713
Info:            Created 
Info:        Working on 1526
Info:            Created 
Info:        Working on 1123
Info:            Created 
Info:        Working on 788
Info:            Created 
Info:        Working on 113
Info:            Created 
Info:        Working on 758
Info:            Created 
Info:        Working on 154
Info:            Created 
Info:        Working on 1078
Info:            Created 
Info:        Working on 1079
Info:            Created 
Info:        Working on 2324
Info:            Created 
Info:        Working on 2739
Info:            Created 
Info:        Working on 3178
Info:            Created 
Info:        Working on 2727
Info:            Created 
Info:        Working on 3651
Info:            Created 
Info:        Working on 3205
Info:            Created 
Info:        Working on 2758
Info:            Created 
Info:        Working on 2335
Info:            Created 
Info:        Working on 1905
Info:            Created 
Info:        Working on 1481
Info:            Created 
Info:        Working on 213
Info:            Created 
Info:        Working on 1467
Info:            Created 
Info:        Working on 315
Info:            Created 
Info:        Working on 486
Info:            Created 
Info:        Working on 2312
Info:            Created 
Info:        Working on 1991
Info:            Created 
Info:        Working on 1714
Info:            Created 
Info:        Working on 2761
Info:            Created 
Info:        Working on 3172
Info:            Created 
Info:        Working on 734
Info:            Created 
Info:        Working on 2719
Info:            Created 
Info:        Working on 1061
Info:            Created 
Info:        Working on 3168
Info:            Created 
Info:        Working on 1458
Info:            Created 
Info:        Working on 4060
Info:            Created 
Info:        Working on 4062
Info:            Created 
Info:        Working on 1874
Info:            Created 
Info:        Working on 383
Info:            Created 
Info:        Working on 384
Info:            Created 
Info:        Working on 582
Info:            Created 
Info:        Working on 1642
Info:            Created 
Info:        Working on 1666
Info:            Created 
Info:        Working on 594
Info:            Created 
Info:        Working on 84
Info:            Created 
Info:        Working on 1190
Info:            Created 
Info:        Working on 119
Info:            Created 
Info:        Working on 834
Info:            Created 
Info:        Working on 1179
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 1172
Info:            Created 
Info:        Working on 1173
Info:            Created 
Info:        Working on 231
Info:            Created 
Info:        Working on 1575
Info:            Created 
Info:        Working on 346
Info:            Created 
Info:        Working on 538
Info:            Created 
Info:        Working on 806
Info:            Created 
Info:        Working on 1147
Info:            Created 
Info:        Working on 1557
Info:            Created 
Info:        Working on 1976
Info:            Created 
Info:        Working on 2062
Info:            Created 
Info:        Working on 2467
Info:            Created 
Info:        Working on 2570
Info:            Created 
Info:        Working on 2170
Info:            Created 
Info:        Working on 2575
Info:            Created 
Info:        Working on 3021
Info:            Created 
Info:        Working on 3488
Info:            Created 
Info:        Working on 1523
Info:            Created 
Info:        Working on 1941
Info:            Created 
Info:        Working on 1516
Info:            Created 
Info:        Working on 2783
Info:            Created 
Info:        Working on 1950
Info:            Created 
Info:        Working on 1943
Info:            Created 
Info:        Working on 2799
Info:            Created 
Info:        Working on 2800
Info:            Created 
Info:        Working on 2789
Info:            Created 
Info:        Working on 2368
Info:            Created 
Info:        Working on 3221
Info:            Created 
Info:        Working on 3230
Info:            Created 
Info:        Working on 1939
Info:            Created 
Info:        Working on 1689
Info:            Created 
Info:        Working on 2101
Info:            Created 
Info:        Working on 897
Info:            Created 
Info:        Working on 1268
Info:            Created 
Info:        Working on 3184
Info:            Created 
Info:        Working on 4095
Info:            Created 
Info:        Working on 4500
Info:            Created 
Info:        Working on 4861
Info:            Created 
Info:        Working on 5128
Info:            Created 
Info:        Working on 5106
Info:            Created 
Info:        Working on 5338
Info:            Created 
Info:        Working on 5562
Info:            Created 
Info:        Working on 5745
Info:            Created 
Info:        Working on 5524
Info:            Created 
Info:        Working on 5297
Info:            Created 
Info:        Working on 5066
Info:            Created 
Info:        Working on 5090
Info:            Created 
Info:        Working on 4803
Info:            Created 
Info:        Working on 4420
Info:            Created 
Info:        Working on 3979
Info:            Created 
Info:        Working on 3056
Info:            Created 
Info:        Working on 3161
Info:            Created 
Info:        Working on 3921
Info:            Created 
Info:        Working on 4352
Info:            Created 
Info:        Working on 4202
Info:            Created 
Info:        Working on 3765
Info:            Created 
Info:        Working on 3626
Info:            Created 
Info:        Working on 1693
Info:            Created 
Info:        Working on 3914
Info:            Created 
Info:        Working on 3915
Info:            Created 
Info:        Working on 4346
Info:            Created 
Info:        Working on 2114
Info:            Created 
Info:        Working on 4344
Info:            Created 
Info:        Working on 4345
Info:            Created 
Info:        Working on 4723
Info:            Created 
Info:        Working on 5024
Info:            Created 
Info:        Working on 5240
Info:            Created 
Info:        Working on 5444
Info:            Created 
Info:        Working on 5642
Info:            Created 
Info:        Working on 5833
Info:            Created 
Info:        Working on 5665
Info:            Created 
Info:        Working on 5854
Info:            Created 
Info:        Working on 6195
Info:            Created 
Info:        Working on 6354
Info:            Created 
Info:        Working on 6470
Info:            Created 
Info:        Working on 6532
Info:            Created 
Info:        Working on 6521
Info:            Created 
Info:        Working on 6327
Info:            Created 
Info:        Working on 6204
Info:            Created 
Info:        Working on 6476
Info:            Created 
Info:        Working on 6388
Info:            Created 
Info:        Working on 6263
Info:            Created 
Info:        Working on 6120
Info:            Created 
Info:        Working on 5972
Info:            Created 
Info:        Working on 5683
Info:            Created 
Info:        Working on 5478
Info:            Created 
Info:        Working on 5139
Info:            Created 
Info:        Working on 4512
Info:            Created 
Info:        Working on 4509
Info:            Created 
Info:        Working on 4881
Info:            Created 
Info:        Working on 4821
Info:            Created 
Info:        Working on 4444
Info:            Created 
Info:        Working on 4440
Info:            Created 
Info:        Working on 2520
Info:            Created 
Info:        Working on 4710
Info:            Created 
Info:        Working on 4711
Info:            Created 
Info:        Working on 2970
Info:            Created 
Info:        Working on 2843
Info:            Created 
Info:        Working on 1663
Info:            Created 
Info:        Working on 2078
Info:            Created 
Info:        Working on 2564
Info:            Created 
Info:        Working on 3485
Info:            Created 
Info:        Working on 2477
Info:            Created 
Info:        Working on 1230
Info:            Created 
Info:        Working on 1350
Info:            Created 
Info:        Working on 2512
Info:            Created 
Info:        Working on 3299
Info:            Created 
Info:        Working on 3749
Info:            Created 
Info:        Working on 4195
Info:            Created 
Info:        Working on 4607
Info:            Created 
Info:        Working on 4946
Info:            Created 
Info:        Working on 4940
Info:            Created 
Info:        Working on 4596
Info:            Created 
Info:        Working on 4182
Info:            Created 
Info:        Working on 3737
Info:            Created 
Info:        Working on 3289
Info:            Created 
Info:        Working on 2013
Info:            Created 
Info:        Working on 2836
Info:            Created 
Info:        Working on 3278
Info:            Created 
Info:        Working on 3723
Info:            Created 
Info:        Working on 4159
Info:            Created 
Info:        Working on 4561
Info:            Created 
Info:        Working on 4901
Info:            Created 
Info:        Working on 4693
Info:            Created 
Info:        Working on 4307
Info:            Created 
Info:        Working on 3874
Info:            Created 
Info:        Working on 3425
Info:            Created 
Info:        Working on 2961
Info:            Created 
Info:        Working on 1765
Info:            Created 
Info:        Working on 2775
Info:            Created 
Info:        Working on 2179
Info:            Created 
Info:        Working on 3669
Info:            Created 
Info:        Working on 4381
Info:            Created 
Info:        Working on 3682
Info:            Created 
Info:        Working on 4523
Info:            Created 
Info:        Working on 4878
Info:            Created 
Info:        Working on 4504
Info:            Created 
Info:        Working on 4112
Info:            Created 
Info:        Working on 4876
Info:            Created 
Info:        Working on 5043
Info:            Created 
Info:        Working on 4755
Info:            Created 
Info:        Working on 2583
Info:            Created 
Info:        Working on 3212
Info:            Created 
Info:        Working on 3026
Info:            Created 
Info:        Working on 2441
Info:            Created 
Info:        Working on 2880
Info:            Created 
Info:        Working on 4212
Info:            Created 
Info:        Working on 4619
Info:            Created 
Info:        Working on 4953
Info:            Created 
Info:        Working on 5008
Info:            Created 
Info:        Working on 4703
Info:            Created 
Info:        Working on 4323
Info:            Created 
Info:        Working on 4049
Info:            Created 
Info:        Working on 2286
Info:            Created 
Info:        Working on 3148
Info:            Created 
Info:        Working on 4044
Info:            Created 
Info:        Working on 4457
Info:            Created 
Info:        Working on 4298
Info:            Created 
Info:        Working on 3414
Info:            Created 
Info:        Working on 3413
Info:            Created 
Info:        Working on 3854
Info:            Created 
Info:        Working on 3777
Info:            Created 
Info:        Working on 3338
Info:            Created 
Info:        Working on 2891
Info:            Created 
Info:        Working on 2451
Info:            Created 
Info:        Working on 2039
Info:            Created 
Info:        Working on 1619
Info:            Created 
Info:        Working on 3801
Info:            Created 
Info:        Working on 3560
Info:            Created 
Info:        Working on 4241
Info:            Created 
Info:        Working on 4645
Info:            Created 
Info:        Working on 4811
Info:            Created 
Info:        Working on 4020
Info:            Created 
Info:        Working on 3121
Info:            Created 
Info:        Working on 4438
Info:            Created 
Info:        Working on 4454
Info:            Created 
Info:        Working on 4037
Info:            Created 
Info:        Working on 3586
Info:            Created 
Info:        Working on 2685
Info:            Created 
Info:        Working on 2668
Info:            Created 
Info:        Working on 2043
Info:            Created 
Info:        Working on 3106
Info:            Created 
Info:        Working on 2454
Info:            Created 
Info:        Working on 4216
Info:            Created 
Info:        Working on 4622
Info:            Created 
Info:        Working on 4292
Info:            Created 
Info:        Working on 4291
Info:            Created 
Info:        Working on 3861
Info:            Created 
Info:        Working on 3859
Info:            Created 
Info:        Working on 4687
Info:            Created 
Info:        Working on 5200
Info:            Created 
Info:        Working on 5222
Info:            Created 
Info:        Working on 4995
Info:            Created 
Info:        Working on 4683
Info:            Created 
Info:        Working on 4967
Info:            Created 
Info:        Working on 2897
Info:            Created 
Info:        Working on 3345
Info:            Created 
Info:        Working on 3791
Info:            Created 
Info:        Working on 5005
Info:            Created 
Info:        Working on 4928
Info:            Created 
Info:        Working on 5227
Info:            Created 
Info:        Working on 5385
Info:            Created 
Info:        Working on 5164
Info:            Created 
Info:        Working on 4909
Info:            Created 
Info:        Working on 4573
Info:            Created 
Info:        Working on 4917
Info:            Created 
Info:        Working on 5398
Info:            Created 
Info:        Working on 5612
Info:            Created 
Info:        Working on 5815
Info:            Created 
Info:        Working on 5410
Info:            Created 
Info:        Working on 4231
Info:            Created 
Info:        Working on 4639
Info:            Created 
Info:        Working on 4567
Info:            Created 
Info:        Working on 3183
Info:            Created 
Info:        Working on 3630
Info:            Created 
Info:        Working on 4064
Info:            Created 
Info:        Working on 1450
Info:            Created 
Info:        Working on 1868
Info:            Created 
Info:        Working on 1057
Info:            Created 
Info:        Working on 1454
Info:            Created 
Info:        Working on 1870
Info:            Created 
Info:        Working on 1256
Info:            Created 
Info:        Working on 1681
Info:            Created 
Info:        Working on 2097
Info:            Created 
Info:        Working on 2498
Info:            Created 
Info:        Working on 4684
Info:            Created 
Info:        Working on 4998
Info:            Created 
Info:        Working on 2939
Info:            Created 
Info:        Working on 4996
Info:            Created 
Info:        Working on 3393
Info:            Created 
Info:        Working on 5223
Info:            Created 
Info:        Working on 3841
Info:            Created 
Info:        Working on 4962
Info:            Created 
Info:        Working on 4277
Info:            Created 
Info:        Working on 4633
Info:            Created 
Info:        Working on 4243
Info:            Created 
Info:        Working on 3788
Info:            Created 
Info:        Working on 3787
Info:            Created 
Info:        Working on 4227
Info:            Created 
Info:        Working on 4637
Info:            Created 
Info:        Working on 4965
Info:            Created 
Info:        Working on 4907
Info:            Created 
Info:        Working on 4929
Info:            Created 
Info:        Working on 5168
Info:            Created 
Info:        Working on 3756
Info:            Created 
Info:        Working on 4199
Info:            Created 
Info:        Working on 4171
Info:            Created 
Info:        Working on 5411
Info:            Created 
Info:        Working on 4586
Info:            Created 
Info:        Working on 5818
Info:            Created 
Info:        Working on 4933
Info:            Created 
Info:        Working on 5819
Info:            Created 
Info:        Working on 5189
Info:            Created 
Info:        Working on 5608
Info:            Created 
Info:        Working on 5413
Info:            Created 
Info:        Working on 5391
Info:            Created 
Info:        Working on 4487
Info:            Created 
Info:        Working on 4087
Info:            Created 
Info:        Working on 4840
Info:            Created 
Info:        Working on 4489
Info:            Created 
Info:        Working on 5110
Info:            Created 
Info:        Working on 5339
Info:            Created 
Info:        Working on 5112
Info:            Created 
Info:        Working on 5359
Info:            Created 
Info:        Working on 5360
Info:            Created 
Info:        Working on 5573
Info:            Created 
Info:        Working on 5777
Info:            Created 
Info:        Working on 5784
Info:            Created 
Info:        Working on 5581
Info:            Created 
Info:        Working on 4485
Info:            Created 
Info:        Working on 4851
Info:            Created 
Info:        Working on 5126
Info:            Created 
Info:        Working on 5131
Info:            Created 
Info:        Working on 4865
Info:            Created 
Info:        Working on 5790
Info:            Created 
Info:        Working on 5791
Info:            Created 
Info:        Working on 5134
Info:            Created 
Info:        Working on 5962
Info:            Created 
Info:        Working on 5363
Info:            Created 
Info:        Working on 6108
Info:            Created 
Info:        Working on 5590
Info:            Created 
Info:        Working on 6106
Info:            Created 
Info:        Working on 5793
Info:            Created 
Info:        Working on 5956
Info:            Created 
Info:        Working on 5955
Info:            Created 
Info:        Working on 5781
Info:            Created 
Info:        Working on 4787
Info:            Created 
Info:        Working on 4776
Info:            Created 
Info:        Working on 4410
Info:            Created 
Info:        Working on 3971
Info:            Created 
Info:        Working on 5069
Info:            Created 
Info:        Working on 5298
Info:            Created 
Info:        Working on 5073
Info:            Created 
Info:        Working on 5322
Info:            Created 
Info:        Working on 5323
Info:            Created 
Info:        Working on 5536
Info:            Created 
Info:        Working on 5750
Info:            Created 
Info:        Working on 5756
Info:            Created 
Info:        Working on 5545
Info:            Created 
Info:        Working on 4408
Info:            Created 
Info:        Working on 4794
Info:            Created 
Info:        Working on 5088
Info:            Created 
Info:        Working on 5325
Info:            Created 
Info:        Working on 5302
Info:            Created 
Info:        Working on 5764
Info:            Created 
Info:        Working on 5940
Info:            Created 
Info:        Working on 5526
Info:            Created 
Info:        Working on 5763
Info:            Created 
Info:        Working on 5553
Info:            Created 
Info:        Working on 5945
Info:            Created 
Info:        Working on 5761
Info:            Created 
Info:        Working on 5890
Info:            Created 
Info:        Working on 5943
Info:            Created 
Info:        Working on 5889
Info:            Created 
Info:        Working on 6073
Info:            Created 
Info:        Working on 5938
Info:            Created 
Info:        Working on 6367
Info:            Created 
Info:        Working on 6049
Info:            Created 
Info:        Working on 5873
Info:            Created 
Info:        Working on 6213
Info:            Created 
Info:        Working on 6391
Info:            Created 
Info:        Working on 6487
Info:            Created 
Info:        Working on 6479
Info:            Created 
Info:        Working on 6416
Info:            Created 
Info:        Working on 6494
Info:            Created 
Info:        Working on 6415
Info:            Created 
Info:        Working on 6502
Info:            Created 
Info:        Working on 6542
Info:            Created 
Info:        Working on 6540
Info:            Created 
Info:        Working on 6102
Info:            Created 
Info:        Working on 6250
Info:            Created 
Info:        Working on 6054
Info:            Created 
Info:        Working on 6216
Info:            Created 
Info:        Working on 6372
Info:            Created 
Info:        Working on 6484
Info:            Created 
Info:        Working on 6268
Info:            Created 
Info:        Working on 6278
Info:            Created 
Info:        Working on 6141
Info:            Created 
Info:        Working on 6394
Info:            Created 
Info:        Working on 6401
Info:            Created 
Info:        Working on 6490
Info:            Created 
Info:        Working on 6407
Info:            Created 
Info:        Working on 6539
Info:            Created 
Info:        Working on 6287
Info:            Created 
Info:        Working on 6500
Info:            Created 
Info:        Working on 6142
Info:            Created 
Info:        Working on 6413
Info:            Created 
Info:        Working on 6295
Info:            Created 
Info:        Working on 5453
Info:            Created 
Info:        Working on 5257
Info:            Created 
Info:        Working on 5471
Info:            Created 
Info:        Working on 5856
Info:            Created 
Info:        Working on 6010
Info:            Created 
Info:        Working on 5838
Info:            Created 
Info:        Working on 5650
Info:            Created 
Info:        Working on 6076
Info:            Created 
Info:        Working on 6197
Info:            Created 
Info:        Working on 5914
Info:            Created 
Info:        Working on 5913
Info:            Created 
Info:        Working on 6083
Info:            Created 
Info:        Working on 6235
Info:            Created 
Info:        Working on 5673
Info:            Created 
Info:        Working on 5247
Info:            Created 
Info:        Working on 5457
Info:            Created 
Info:        Working on 5655
Info:            Created 
Info:        Working on 5648
Info:            Created 
Info:        Working on 5451
Info:            Created 
Info:        Working on 5653
Info:            Created 
Info:        Working on 5896
Info:            Created 
Info:        Working on 5711
Info:            Created 
Info:        Working on 5841
Info:            Created 
Info:        Working on 5905
Info:            Created 
Info:        Working on 6012
Info:            Created 
Info:        Working on 5720
Info:            Created 
Info:        Working on 6081
Info:            Created 
Info:        Working on 5505
Info:            Created 
Info:        Working on 5911
Info:            Created 
Info:        Working on 5504
Info:            Created 
Info:        Working on 5728
Info:            Created 
Info:        Working on 5901
Info:            Created 
Info:        Working on 5555
Info:            Created 
Info:        Working on 5331
Info:            Created 
Info:        Working on 5517
Info:            Created 
Info:        Working on 5290
Info:            Created 
Info:        Working on 5917
Info:            Created 
Info:        Working on 6084
Info:            Created 
Info:        Working on 5919
Info:            Created 
Info:        Working on 6098
Info:            Created 
Info:        Working on 6099
Info:            Created 
Info:        Working on 6240
Info:            Created 
Info:        Working on 6381
Info:            Created 
Info:        Working on 6382
Info:            Created 
Info:        Working on 6247
Info:            Created 
Info:        Working on 5515
Info:            Created 
Info:        Working on 5743
Info:            Created 
Info:        Working on 5933
Info:            Created 
Info:        Working on 5947
Info:            Created 
Info:        Working on 5769
Info:            Created 
Info:        Working on 6221
Info:            Created 
Info:        Working on 6070
Info:            Created 
Info:        Working on 5950
Info:            Created 
Info:        Working on 6374
Info:            Created 
Info:        Working on 6105
Info:            Created 
Info:        Working on 6376
Info:            Created 
Info:        Working on 6253
Info:            Created 
Info:        Working on 6229
Info:            Created 
Info:        Working on 6385
Info:            Created 
Info:        Working on 6071
Info:            Created 
Info:        Working on 6379
Info:            Created 
Info:        Working on 6233
Info:            Created 
Info:        Working on 6340
Info:            Created 
Info:        Working on 6025
Info:            Created 
Info:        Working on 6180
Info:            Created 
Info:        Working on 6453
Info:            Created 
Info:        Working on 6525
Info:            Created 
Info:        Working on 6550
Info:            Created 
Info:        Working on 6527
Info:            Created 
Info:        Working on 6442
Info:            Created 
Info:        Working on 6511
Info:            Created 
Info:        Working on 6441
Info:            Created 
Info:        Working on 6519
Info:            Created 
Info:        Working on 6549
Info:            Created 
Info:        Working on 6547
Info:            Created 
Info:        Working on 6338
Info:            Created 
Info:        Working on 6187
Info:            Created 
Info:        Working on 6343
Info:            Created 
Info:        Working on 6462
Info:            Created 
Info:        Working on 6530
Info:            Created 
Info:        Working on 6474
Info:            Created 
Info:        Working on 6535
Info:            Created 
Info:        Working on 6306
Info:            Created 
Info:        Working on 6162
Info:            Created 
Info:        Working on 6429
Info:            Created 
Info:        Working on 6424
Info:            Created 
Info:        Working on 6509
Info:            Created 
Info:        Working on 6433
Info:            Created 
Info:        Working on 6545
Info:            Created 
Info:        Working on 6315
Info:            Created 
Info:        Working on 6517
Info:            Created 
Info:        Working on 6163
Info:            Created 
Info:        Working on 6439
Info:            Created 
Info:        Working on 6323
Info:            Created 
Info:        Working on 2744
Info:            Created 
Info:        Working on 3187
Info:            Created 
Info:        Working on 3633
Info:            Created 
Info:        Working on 4066
Info:            Created 
Info:        Working on 4004
Info:            Created 
Info:        Working on 4425
Info:            Created 
Info:        Working on 3538
Info:            Created 
Info:        Working on 3545
Info:            Created 
Info:        Working on 4423
Info:            Created 
Info:        Working on 4807
Info:            Created 
Info:        Working on 5093
Info:            Created 
Info:        Working on 4527
Info:            Created 
Info:        Working on 4526
Info:            Created 
Info:        Working on 5141
Info:            Created 
Info:        Working on 3681
Info:            Created 
Info:        Working on 4529
Info:            Created 
Info:        Working on 3239
Info:            Created 
Info:        Working on 4124
Info:            Created 
Info:        Working on 3685
Info:            Created 
Info:        Working on 4130
Info:            Created 
Info:        Working on 4531
Info:            Created 
Info:        Working on 4350
Info:            Created 
Info:        Working on 4814
Info:            Created 
Info:        Working on 4456
Info:            Created 
Info:        Working on 4729
Info:            Created 
Info:        Working on 4437
Info:            Created 
Info:        Working on 5032
Info:            Created 
Info:        Working on 3566
Info:            Created 
Info:        Working on 4013
Info:            Created 
Info:        Working on 3127
Info:            Created 
Info:        Working on 2676
Info:            Created 
Info:        Working on 1857
Info:            Created 
Info:        Working on 1855
Info:            Created 
Info:        Working on 4028
Info:            Created 
Info:        Working on 2277
Info:            Created 
Info:        Working on 2688
Info:            Created 
Info:        Working on 2620
Info:            Created 
Info:        Working on 3059
Info:            Created 
Info:        Working on 3508
Info:            Created 
Info:        Working on 3506
Info:            Created 
Info:        Working on 3951
Info:            Created 
Info:        Working on 4385
Info:            Created 
Info:        Working on 4758
Info:            Created 
Info:        Working on 5047
Info:            Created 
Info:        Working on 5266
Info:            Created 
Info:        Working on 5158
Info:            Created 
Info:        Working on 5382
Info:            Created 
Info:        Working on 5379
Info:            Created 
Info:        Working on 5406
Info:            Created 
Info:        Working on 3678
Info:            Created 
Info:        Working on 2457
Info:            Created 
Info:        Working on 1631
Info:            Created 
Info:        Working on 3341
Info:            Created 
Info:        Working on 2052
Info:            Created 
Info:        Working on 2461
Info:            Created 
Info:        Working on 4051
Info:            Created 
Info:        Working on 2907
Info:            Created 
Info:        Working on 3147
Info:            Created 
Info:        Working on 3357
Info:            Created 
Info:        Working on 3609
Info:            Created 
Info:        Working on 4057
Info:            Created 
Info:        Working on 3806
Info:            Created 
Info:        Working on 4135
Info:            Created 
Info:        Working on 4245
Info:            Created 
Info:        Working on 3694
Info:            Created 
Info:        Working on 4535
Info:            Created 
Info:        Working on 3244
Info:            Created 
Info:        Working on 4132
Info:            Created 
Info:        Working on 3877
Info:            Created 
Info:        Working on 4310
Info:            Created 
Info:        Working on 3307
Info:            Created 
Info:        Working on 3726
Info:            Created 
Info:        Working on 2424
Info:            Created 
Info:        Working on 2862
Info:            Created 
Info:        Working on 2009
Info:            Created 
Info:        Working on 1594
Info:            Created 
Info:        Working on 3752
Info:            Created 
Info:        Working on 3917
Info:            Created 
Info:        Working on 2017
Info:            Created 
Info:        Working on 3462
Info:            Created 
Info:        Working on 2431
Info:            Created 
Info:        Working on 2997
Info:            Created 
Info:        Working on 2866
Info:            Created 
Info:        Working on 3936
Info:            Created 
Info:        Working on 3935
Info:            Created 
Info:        Working on 3311
Info:            Created 
Info:        Working on 4356
Info:            Created 
Info:        Working on 5431
Info:            Created 
Info:        Working on 5430
Info:            Created 
Info:        Working on 4359
Info:            Created 
Info:        Working on 3759
Info:            Created 
Info:        Working on 3175
Info:            Created 
Info:        Working on 3625
Info:            Created 
Info:        Working on 2808
Info:            Created 
Info:        Working on 3246
Info:            Created 
Info:        Working on 2701
Info:            Created 
Info:        Working on 3150
Info:            Created 
Info:        Working on 3466
Info:            Created 
Info:        Working on 2553
Info:            Created 
Info:        Working on 3005
Info:            Created 
Info:        Working on 3479
Info:            Created 
Info:        Working on 2291
Info:            Created 
Info:        Working on 2706
Info:            Created 
Info:        Working on 3157
Info:            Created 
Info:        Working on 1959
Info:            Created 
Info:        Working on 1538
Info:            Created 
Info:        Working on 1954
Info:            Created 
Info:        Working on 2385
Info:            Created 
Info:        Working on 1769
Info:            Created 
Info:        Working on 2183
Info:            Created 
Info:        Working on 2110
Info:            Created 
Info:        Working on 2516
Info:            Created 
Info:        Working on 2966
Info:            Created 
Info:        Working on 3431
Info:            Created 
Info:        Working on 3881
Info:            Created 
Info:        Working on 4314
Info:            Created 
Info:        Working on 4697
Info:            Created 
Info:        Working on 4552
Info:            Created 
Info:        Working on 3773
Info:            Created 
Info:        Working on 3327
Info:            Created 
Info:        Working on 3775
Info:            Created 
Info:        Working on 4185
Info:            Created 
Info:        Working on 4599
Info:            Created 
Info:        Working on 4943
Info:            Created 
Info:        Working on 5194
Info:            Created 
Info:        Working on 5418
Info:            Created 
Info:        Working on 5197
Info:            Created 
Info:        Working on 4949
Info:            Created 
Info:        Working on 4610
Info:            Created 
Info:        Working on 4198
Info:            Created 
Info:        Working on 3427
Info:            Created 
Info:        Working on 3373
Info:            Created 
Info:        Working on 3825
Info:            Created 
Info:        Working on 4264
Info:            Created 
Info:        Working on 4657
Info:            Created 
Info:        Working on 1442
Info:            Created 
Info:        Working on 1606
Info:            Created 
Info:        Working on 2025
Info:            Created 
Info:        Working on 1532
Info:            Created 
Info:        Working on 1952
Info:            Created 
Info:        Working on 2054
Info:            Created 
Info:        Working on 1826
Info:            Created 
Info:        Working on 1422
Info:            Created 
Info:        Working on 1830
Info:            Created 
Info:        Working on 2236
Info:            Created 
Info:        Working on 2644
Info:            Created 
Info:        Working on 2985
Info:            Created 
Info:        Working on 911
Info:            Created 
Info:        Working on 616
Info:            Created 
Info:        Working on 407
Info:            Created 
Info:        Working on 272
Info:            Created 
Info:        Working on 413
Info:            Created 
Info:        Working on 624
Info:            Created 
Info:        Working on 922
Info:            Created 
Info:        Working on 1018
Info:            Created 
Info:        Working on 1400
Info:            Created 
Info:        Working on 1813
Info:            Created 
Info:        Working on 2226
Info:            Created 
Info:        Working on 2631
Info:            Created 
Info:        Working on 3073
Info:            Created 
Info:        Working on 3529
Info:            Created 
Info:        Working on 3981
Info:            Created 
Info:        Working on 599
Info:            Created 
Info:        Working on 2018
Info:            Created 
Info:        Working on 901
Info:            Created 
Info:        Working on 1270
Info:            Created 
Info:        Working on 878
Info:            Created 
Info:        Working on 1732
Info:            Created 
Info:        Working on 1240
Info:            Created 
Info:        Working on 1319
Info:            Created 
Info:        Working on 983
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 3.93471e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Fri Oct 26 23:49:56 2018
